### PR TITLE
Fix development setup

### PR DESCRIPTION
**Pull request by kiootic**

### CODE REVIEW

**Comment by axolotl0212** [comment]
@kiootic got this error when creating app after updating environment variable
```json
{
	"data": null,
	"errors": [
		{
			"message": "invalid resource 'authgear.secrets.yaml': cannot override secret 'oidc' defined in base config",
			"locations": [
				{
					"line": 2,
					"column": 3
				}
			],
			"path": [
				"createApp"
			]
		}
	]
}
```

Updated some config as well?

**Comment by kiootic** [comment]
I suppose the secrets in `authgear.yaml` for local mode is in conflict of the template secrets for k8s mode. Therefore we  should not symlink the k8s secret config to local secret config. Let me change that.

**Comment by axolotl0212** [comment]
hack/k8s-resources/authgear.secrets.yaml missing first line `secret:`

**Review by axolotl0212 — APPROVED** [review]
It works

**Pull request merged**
