### PR TITLE
Add checker for config source integrity

### PR DESCRIPTION
**Pull request by kiootic**
`go run ./cmd/portal internal check config-sources`

ref #3098

### CODE REVIEW

**Comment by louischan-oursky** [comment]
@kiootic I remember you told me you have run this command against the staging server, and found some invalid configs. Did you investigate into that? Any findings?

**Comment by kiootic** [comment]
Some of the configs contain the deprecated field `/authenticator/password/ratelimit`, despite we already run the migration before. However, the current codebase does not set/update the deprecated field, so it's not known how it is still present.

**Comment by louischan-oursky** [comment]
I run again and did not find any invalid configs though. Did you run the migration again?

**Comment by louischan-oursky** [comment]
Oh, I did not apply your another PR first. Sorry.

**Pull request merged**
