### PR TITLE
Separate rate limit buckets of whatsapp and sms in forgot password

### PR DESCRIPTION
**Pull request by tung2744**
ref #3504

### CODE REVIEW

**Review by louischan-oursky — COMMENTED** [review]
Even with this fix, switching back to SMS will still result in rate limit error. But in login, we can switch from password to passwordless back and forth without seeing the rate limit error. Of course, the code was not sent if the cooldown is still counting down.

**Comment by tung2744** [comment]
@louischan-oursky I can switch it immediately in local with the following config:

```yaml
forgot_password:
  enabled: true
  rate_limits:
    email:
      trigger_cooldown: 10s
      validate_per_ip:
        burst: 60
        enabled: true
        period: 1m
    sms:
      trigger_cooldown: 15s
      validate_per_ip:
        burst: 60
        enabled: true
        period: 1m
  valid_periods:
    code: 300s
    link: 1205s
```

https://github.com/authgear/authgear-server/assets/34942210/a7031423-408b-4fa2-a087-c1f82ac23c7f

**Comment by tung2744** [comment]
Oh I see what you mean, let me check check.

**Comment by tung2744** [comment]
@louischan-oursky Updated, thanks!

https://github.com/authgear/authgear-server/assets/34942210/f234898c-8b9e-4463-a1df-83b751d26aee

**Pull request merged**
