### PR TITLE
Show audit log in portal

### PR DESCRIPTION
**Pull request by louischan-oursky**
ref #1214

### CODE REVIEW

**Review by carmenlau — COMMENTED** [review]
The PR overall looks great and I love the way `useTranactionalState` handles the date selection state!

Only 1 comment that we may need to handle when the audit log is not enabled?

**Comment by louischan-oursky** [comment]
Added 2 commits.

**Review by carmenlau — COMMENTED** [review]
@louischan-oursky I think we need to handle when developer doesn't provide `audit.db` in `authgear.secrets.yaml`. Currently, admin api `GraphQLHandler` called `h.AuditDatabase.ReadOnly` and seems we haven't handled the db is not configured case.

**Comment by louischan-oursky** [comment]
Fixed.

**Pull request merged**
