### PR TITLE
Manage authorized app list in settings

### PR DESCRIPTION
**Pull request by carmenlau**
refs #2526

### CODE REVIEW

**Review by louischan-oursky — COMMENTED** [review]
LGTM

**Comment by carmenlau** [comment]
Updated:
1. Hide third-party app sessions from the signed-in sessions list
2. Update the settings page layout based on the project OAuth client settings

**The project has third-party apps**

Screenshot 2022-10-05 at 12 07 23 pm

**The project doesn't have third-party apps**

Screenshot 2022-10-05 at 12 09 18 pm

**Comment by louischan-oursky** [comment]
The terminate group button now appears on the top right corner in the design

**Comment by carmenlau** [comment]
Updated:)

**Pull request merged**
