### PR TITLE
Update resource config pages UI design

### PR DESCRIPTION
**Pull request by kiootic**
ref #748

### CODE REVIEW

**Review by louischan-oursky — COMMENTED** [review]
The only concern I have is that the developer can no longer "reset to default value" by saving an empty template. Is there any way to allow them to reset the template to default value?

**Comment by kiootic** [comment]
I suppose you encountered 'Some required resources do not have localizations in default language' error?

'Default value' for templates are only available for `en` locale templates. Maybe we can make that a special case and allow saving empty templates (i.e. delete app specific template value) for `en` locale.

**Comment by kiootic** [comment]
@louischan-oursky Updated. Now only forbid removing a required resource of default locale which is not the built-in locale (en).

**Comment by louischan-oursky** [comment]
Two bugs

1. Cannot save images
2. Just by changing selected locale, the save button will become enabled.

**Comment by kiootic** [comment]
> Just by changing selected locale, the save button will become enabled.

I can't reproduce this bug, but I've fixed the 'cannot save images' bug, which is actually 'cannot display saved images'.

**Comment by louischan-oursky** [comment]
1. Remove all languages and all templates so that the app does not have any resources
2. Add Chinese Hong Kong, and then save
3. Edit the English version of translation.json, and then save
4. Change selected to Chinese Hong Kong, the save button becomes enabled.

**Pull request merged**
