### PR TITLE
Update ui of delete login id button

### PR DESCRIPTION
**Pull request by tung2744**
ref DEV-1313

### CODE REVIEW

**Comment by louischan-oursky** [comment]
1. Please rebase.
2. Fung has one more comment to be addressed.

**Comment by tung2744** [comment]
Updated, thanks!

**Comment by tung2744** [comment]
Found a bug that if I only have one email, and update email is disabled but delete email is not disabled, we will see a edit button in settings, but inside the edit screen we see no action buttons.
Marking this pr as WIP first.

**Comment by tung2744** [comment]
Fixed

**Review by louischan-oursky — APPROVED** [review]

**Pull request merged**
