### PR TITLE
Expose partial phone number

### PR DESCRIPTION
**Pull request by louischan-oursky**
ref https://github.com/authgear/authgear-server/issues/3873

### CODE REVIEW

**Comment by louischan-oursky** [comment]
This PR remove the validation from the frontend. The partial value is passed to the server. But there are some caveats

1. The input does not forbid invalid characters. So we could save something like `+852abcd`
2. If the input is partial, then spaces are not trimmed, like `+852 9876 43`
3. If the input is valid, then the value is a E.164 without spaces.

**Comment by fungc-io** [comment]
1. Use a pattern to only allow */#/+/digits
2. Trim in frontend before save

**Comment by tung2744** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

I found that pattern seems doesn't enforce the value to be matching the pattern, it only affect validation.

**Comment by louischan-oursky** [comment]
Yes, I also realized that. Added a commit to fix that.

**Review by tung2744 — APPROVED** [review]

**Pull request merged**
