### PR TITLE
Restructure localisation resources setup pages

### PR DESCRIPTION
**Pull request by cychiuae**
ref #4290 
ref #4291 
ref #4334 

ref DEV-1381
ref DEV-1382
ref DEV-1418

@tung2744

### CODE REVIEW

**Comment by tung2744** [comment]
https://github.com/authgear/authgear-server/assets/34942210/e3f05124-d775-464a-ba65-55573f1a7a04

Looks like the color picker preview isn't working?

**Comment by tung2744** [comment]
I checked in the main branch and looks like existing issue, maybe we create another issue to handle it.

**Comment by cychiuae** [comment]
> I checked in the main branch and looks like existing issue, maybe we create another issue to handle it.

Seems like only background color picker doesn't work

**Comment by cychiuae** [comment]
> I checked in the main branch and looks like existing issue, maybe we create another issue to handle it.

Production also has this problem. Let me create a issue for it.

**Comment by cychiuae** [comment]
Created #4346 to follow up

**Review by tung2744 — APPROVED** [review]

**Pull request merged**
