### PR TITLE
Add "include" for executing template as a string

### PR DESCRIPTION
**Pull request by tung2744**
ref #3644 

Usage

```
{{ $errorMessage := include "authflowv2/__error.html" . }}
```

### CODE REVIEW

**Comment by IniZio** [comment]
Not sure if this is intended to generate html content or text node? Currently if run on `authflowv2/__error.html`, it will return as text node `<span>....</span>`

**Comment by tung2744** [comment]
It should return html content. Let me check how to allow html content in go template.

**Comment by louischan-oursky** [comment]
See if this is what you are looking for? https://pkg.go.dev/html/template#HTML

**Comment by IniZio** [comment]
Seems works :adore2x:

```go
func makeInclude(t tpl) func(tplName string, data any) (template.HTML, error) {
	return func(
		tplName string,
		data any,
	) (template.HTML, error) {
		buf := &bytes.Buffer{}
		err := t.ExecuteTemplate(buf, tplName, data)
		return template.HTML(buf.String()), err
	}
}
```

**Comment by tung2744** [comment]
Updated to return HTML :adore:

**Comment by louischan-oursky** [comment]
Can we add some tests?

1. To show that it supports variable template name.
```
{{ $var := "temp2" }}
{{ template "temp1" (dict "Prop1" (include $var (dict "Prop2" "world"))) }}
```

2. To show that it supports HTML

**Comment by tung2744** [comment]
Added two commits to fix linting issues and add tests

**Comment by louischan-oursky** [comment]
Added one more test to showcase nesting.

**Pull request merged**
