### PR TITLE
[OpenCV FR] Fix misc bugs

### PR DESCRIPTION
**Pull request by pkong-ds**
ref DEV-2175

## What's in this PR?

- Fix chrome not able to open camera
- Fix create first person (create collection) will always fail (`app_id` duplicate)

### CODE REVIEW

**Comment by pkong-ds** [comment]
@louischan-oursky local ci pass now after rebase 🙏 Can help run workflow again?

**Comment by pkong-ds** [comment]
Made this depend on PR #4835

**Comment by pkong-ds** [comment]
@louischan-oursky thanks for fixing the import format bug. Can help run workflow again? 🙏

**Comment by pkong-ds** [comment]
@louischan-oursky sor, missed a commit, can help again? 🙇

**Review by louischan-oursky — APPROVED** [review]

**Pull request closed without merging**
