### PR TITLE
Ensure user cannot save a config with empty client id in sso providers

### PR DESCRIPTION
**Pull request by tung2744**
ref #3106

### CODE REVIEW

**Comment by louischan-oursky** [comment]
Have you ever encounter a situation the portal saves an empty client ID? Do you know how to reproduce it?

**Comment by louischan-oursky** [comment]
Oh, just saving an empty client ID will trigger this validation error

**Comment by tung2744** [comment]
@louischan-oursky When the user modified the field, the value of the field is not undefined. Therefore it will pass the schema validation, even it is an empty string.
If the user didn't modify the field, it is undefined but not empty string, in this case validation error will be thrown.

**Comment by louischan-oursky** [comment]
@louischan-oursky Check if preexisting projects will be affected by this change.

**Pull request merged**
