### PR TITLE
Support disable authentication and settings page

### PR DESCRIPTION
**Pull request by IniZio**
ref: #2905

### CODE REVIEW

**Comment by IniZio** [comment]
@louischan-oursky This PR should pass™️

**Comment by louischan-oursky** [comment]
What is the magic?

**Comment by IniZio** [comment]
I just reset soft then make generate per commit, no code change

**Review by louischan-oursky — COMMENTED** [review]
Screenshot 2023-02-13 at 11 27 02 AM

The bottom padding is too little. Apply the same padding from /errors/error

**Comment by IniZio** [comment]
@louischan-oursky Aligned with other pages:

image

However it will look a bit weird with watermark disabled:

image

Seems other pages have similar issue as well e.g. not found page:

image

**Comment by louischan-oursky** [comment]
Forget about the watermark first. Thank you.

**Pull request merged**
