### PR TITLE
Pin the first column of Users List

### PR DESCRIPTION
**Pull request by Ngkaokis**
ref #3982

https://github.com/authgear/authgear-server/assets/63200569/b8a7229c-2b7a-467d-8298-612c50e8b3c7

### CODE REVIEW

**Comment by tung2744** [comment]
What about vertical scrolling of the list?

**Comment by Ngkaokis** [comment]
> What about vertical scrolling of the list?

Can see the demo video. I think just let it scroll as usual?

**Comment by tung2744** [comment]
In your video, the scrollbar appears on the outer body. What I mean is the vertical scrolling "of the table".
But I've tested it and seems working too.

BTW, it seems listWrapper of UsersList is using `flex: 1 0 0%` therefore the scrollbar appeared on incorrect position.

**Comment by Ngkaokis** [comment]
Find problem in mobile screen size. Need to think think how to display the first column :sosad:

 @fungc-io 


https://github.com/authgear/authgear-server/assets/63200569/d7d41168-1898-4ac2-a38d-e547da0e7e0d

**Comment by tung2744** [comment]
I guess we should disable the pin in mobile.

**Comment by fungc-io** [comment]
Right, we better disable the pin if the screen witdth is less than 2 columns.
i.e. if there is not enough space for 1st column + 1 more.

**Comment by Ngkaokis** [comment]
> we better disable the pin if the screen witdth is less than 2 columns.
i.e. if there is not enough space for 1st column + 1 more.

I think we can't determine such situation :derpthink:
just disable it on mobile breakpoint should be enough

**Comment by fungc-io** [comment]
> I think we can't determine such situation :derpthink:
> just disable it on mobile breakpoint should be enough

Yes, that works 👍

**Pull request merged**
