### PR TITLE
Some phone input fixes

### PR DESCRIPTION
**Pull request by tung2744**
ref #3850 #3852 #3853

### CODE REVIEW

**Comment by louischan-oursky** [comment]
I found another bug.

1. Click on the country select, type in 853, press enter to select it.
2. Focus the text input, type in +852. See a warning in the console saying "Trying to select an option which does not exist"

**Comment by tung2744** [comment]
Fixed #3850 in this pr too.

**Comment by tung2744** [comment]
> I found another bug.
> 
> 1. Click on the country select, type in 853, press enter to select it.
> 2. Focus the text input, type in +852. See a warning in the console saying "Trying to select an option which does not exist"

Fixed in [b6854e0](https://github.com/authgear/authgear-server/pull/3860/commits/b6854e02bbef235c1092f56846bf248fed3e73df)

But the warning still appears on initial load, maybe let me open another issue to see how to fix that.

**Comment by louischan-oursky** [comment]
But now I cannot press enter to select the first item in the filtered list :(

**Comment by louischan-oursky** [comment]
Can we refactor so that

1. When the search box is focus, the list shows filtered items.
2. When the search box is focus, the first item in the list is selected.
3. When the search box is focus, pressing enter selects the first item (if there is at least one item). Otherwise, it is no-op.
4. Calling the API to select an item WILL NOT be affected by the search box. I think we need to maintain two lists. One is full, another one is filtered.

**Comment by tung2744** [comment]
> But now I cannot press enter to select the first item in the filtered list :(

Fixed in bfea421

We actually already have two lists, the bug is caused by I forgot to compute the correct selected item in search mode.

**Comment by louischan-oursky** [comment]
The handling of highlighted item in the list still has problem.

Proposed solution

- Introduce `private highlightIndex: number` in customSelect
- When searchTarget value changes, set highlightIndex to 0
- When Up or Down is hit, decrement or increment highlightIndex with bound checking

**Comment by tung2744** [comment]
@louischan-oursky Updated again, thanks!

**Pull request merged**
