### PR TITLE
Fix reauthentication on portal

### PR DESCRIPTION
**Pull request by louischan-oursky**
ref #3267

### CODE REVIEW

**Review by tung2744 — COMMENTED** [review]
This pr modified frontend only, but I think user is still unable to visit the secret because he is unable to generate the visit token?
https://github.com/authgear/authgear-server/blob/main/pkg/portal/service/app.go#L236

**Comment by louischan-oursky** [comment]
```
	if !(elapsed >= 0 && elapsed < 5*time.Minute || !sessionInfo.UserCanReauthenticate) {
		return nil, ErrReauthRequrired
	}
```

- `elapsed >= 0 && elapsed < 5*time.Minute` means authenticated recently
- `!sessionInfo.UserCanReauthenticate` means cannot re-authenticate
- `!(a || b)` means `!a && !b`
- So overall the if condition means **NOT** authenticated recently **AND** can re-authenticate
- Therefore, those who cannot re-authenticate can always create the token.

**Comment by tung2744** [comment]
Oh you are right, I missed the ! before the two conditions.

**Comment by louischan-oursky** [comment]
That condition is really hard to read. It is not your fault :)

**Pull request merged**
