### PR TITLE
Return entity reference only in mutating service facade functions

### LINKED ISSUE #568: Add time for username is always at 1/1/1, 7:36 AM
When try to add a username under "Add Identity" dropdown, will see the add time is 1/1/1 7:36AM. But the date time will change to a correct one after page reload

Screenshot 2020-10-23 at 14 17 20

### PR DESCRIPTION
**Pull request by kiootic**
fix #568

### CODE REVIEW

**Review by louischan-oursky — COMMENTED** [review]
I am curious of why it did not work as expected. Any details?

**Comment by kiootic** [comment]
We pass the new `*identity.Info` to service through facade. The service translates the `*identity.Info` to the concrete type of each identity type (e.g. `*loginid.Identiy`), the specific identity type provider then populate the timestamps before updating database. Therefore, the updated timestamp did not propagated back to the passed in `*identity.Info`.

**Comment by louischan-oursky** [comment]
Can we instead ensure the returned Info has latest information?

**Comment by kiootic** [comment]
I'd prefer the updated approach, so that all resolved entity data comes from loaders instead of from service directly.

**Pull request merged**
