### PR TITLE
Fix delete confirmation text being translated

### PR DESCRIPTION
**Pull request by randy1yu**
ref #4212 
ref DEV-1293

### CODE REVIEW

**Review by louischan-oursky — COMMENTED** [review]
I picked Italian to test. And found that it will crash in the confirmation delete page with Italian. I further discover that in the it/translation.json, there are some malformed Simplified Chinese translation causing the crash. Can you re-generate the Italian translation?

**Comment by randy1yu** [comment]
> I picked Italian to test. And found that it will crash in the confirmation delete page with Italian. I further discover that in the it/translation.json, there are some malformed Simplified Chinese translation causing the crash. Can you re-generate the Italian translation?

Regenerating for few times but some result seems still wrong, I think it's because ai misunderstood locale code `it`.
Maybe it's helpful to add locale name to the prompt.

**Comment by louischan-oursky** [comment]
We have `name` in the mapping https://github.com/authgear/authgear-server/blob/main/scripts/python/generate_translations.py#L17

But the name is not canonical. The canonical names can be obtained from `scripts/npm/node_modules/cldr-localenames-modern/main/en/languages.json`. Let's copy the names from `scripts/npm/node_modules/cldr-localenames-modern/main/en/languages.json` to our mapping. And then update the prompt to use the canonical name instead of the 2-letter language identifier. See if this approves anything.

**Comment by randy1yu** [comment]
Updated

> And then update the prompt to use the canonical name instead of the 2-letter language identifier. See if this approves anything.

It looks better for Italian.

**Review by louischan-oursky — APPROVED** [review]

**Pull request merged**
