### PR TITLE
Fix disconnecting wechat and disconnecting last identity

### PR DESCRIPTION
**Pull request by louischan-oursky**
ref #3281

### CODE REVIEW

**Comment by fungc-io** [comment]
@louischan-oursky let's show the user id for wechat instead of just "WeChat" in the portal

**Comment by fungc-io** [comment]
@tung2744 Please let me know after this fix is merged and deployed to staging, so we can ask Joyz to try again

**Comment by louischan-oursky** [comment]
@tung2744 Added a commit to show subject ID if email is absent.

**Comment by louischan-oursky** [comment]
@fungc-io Deployed

**Pull request merged**
