### PR TITLE
Support ui_locales and state in workflow

### PR DESCRIPTION
**Pull request by tung2744**

### CODE REVIEW

**Review by louischan-oursky — COMMENTED** [review]
Looks good to me so far

**Comment by tung2744** [comment]
@louischan-oursky I found that we may need to enable users to encode `state` and `ui_locales` in the email template, because they are arbitrary data that given by the user so is possible to contain characters that are invalid as query parameter. Therefore I added `EncodableData` in the latest commit. See if any concern?

The expected usage is
```
{{ .State.URLQueryEncoded }} // encoded
{{ .State }} // raw
```

**Comment by louischan-oursky** [comment]
html/template should be smart enough to handle that. See https://go.dev/play/p/VOC-jIDDuV-

**Comment by tung2744** [comment]
@louischan-oursky However we also have text templates? https://go.dev/play/p/DT5MPXBq2IG

**Comment by louischan-oursky** [comment]
I suggest we add a func `queryEscape` which is https://pkg.go.dev/net/url#QueryEscape so the writer can write `{{ .State | queryEscape }}`

**Comment by tung2744** [comment]
@louischan-oursky If using pipes, there is a provided `urlquery` pipe can be used. But I saw some effort was made to disallow pipes in templates.
https://github.com/authgear/authgear-server/blob/2023C01/pkg/util/template/validation.go#L109

**Comment by louischan-oursky** [comment]
where does `urlquery` come from?

**Comment by tung2744** [comment]
@louischan-oursky https://pkg.go.dev/text/template#hdr-Functions Should be a predefined function

**Comment by louischan-oursky** [comment]
@kiootic Do you remember why we disallowed pipe back in that time?

**Comment by kiootic** [comment]
Pipes could be used to consume lots of memory/CPU and DoS the server.

**Comment by louischan-oursky** [comment]
Since we have context on where state and ui_locales will appear. I suggest we do something like https://go.dev/play/p/y-zrEPaCjuR

**Comment by tung2744** [comment]
🤔 If we assume the state must be put back into query of some url, then this can be a solution.

**Comment by tung2744** [comment]
@louischan-oursky Updated, thanks!

**Pull request merged**
