### PR TITLE
Make error message bar stick to top

### PR DESCRIPTION
**Pull request by tung2744**
ref #3445

### CODE REVIEW

**Comment by louischan-oursky** [comment]
We can use `fixed` instead of `sticky`. `fixed` works well on mobile Safari.

**Comment by tung2744** [comment]
https://github.com/authgear/authgear-server/assets/34942210/7acfd6d1-d553-4ccb-a584-a0ead928398d

@louischan-oursky This is the effect of using fixed, it doesn't work too. The problem is the webview is scrolled by "something" outside the body element when keyboard is shown. All things in the screen will be scrolled.

**Comment by fungc-io** [comment]
Seems like Webkit really hate it when we stick the elements on the top... 😞

**Comment by tung2744** [comment]
https://github.com/authgear/authgear-server/assets/34942210/0bd61b60-99e6-46ba-a9eb-19515cb75e74

It seems even using position fixed, the message bar is still not always visible.

**Comment by fungc-io** [comment]
Let's try make it not autofocus when error message is present

**Comment by louischan-oursky** [comment]
I am closing this PR because we will go for another approach.

**Pull request closed without merging**
