### PR TITLE
Fix portal handling for empty default localization

### PR DESCRIPTION
**Pull request by IniZio**
ref #3627

### CODE REVIEW

**Comment by louischan-oursky** [comment]
The fix should be 

> do not let user choose the language before save.

**Review by louischan-oursky — COMMENTED** [review]
- Remove the prop `supportedLanguages` of ResourcesConfigurationContent in UISettingsScreen.tsx. It is because `supportedLanguages` duplicates with `configForm.state.supportedLanguages`
- Remove the prop `supportedLanguages` of ResourcesConfigurationContent in LocalizationConfigurationScreen.tsx. Same reason.
- Remove `supportedLanguages` from ManageLanguageWidget. Add `supportedLanguagesForDropdown` and `supportedLanguagesForEditing`

**Comment by IniZio** [comment]
The root cause was not actually because the language was selected before save, it was because currently a language with empty resource is initialized on frontend with default language.

Since user selected a new language as default, it will fallback the resource json with itself which is still null, ending in this error.

**Comment by IniZio** [comment]
After discussion, will use en as the last fallback instead of empty string.

**Comment by louischan-oursky** [comment]
1. Implement the changes described in https://github.com/authgear/authgear-server/pull/3881#pullrequestreview-1915907751
2. Cannot remove language.
Screenshot 2024-03-06 at 12 38 16

**Pull request merged**
