### PR TITLE
Implement settings screen session tab

### LINKED ISSUE #529: [UI] Implement settings screen session tab
- [x] Create session settings tab
  - [x] Add persistent cookie toggle
  - [x] Add session lifetime input
  - [x] Add idle timeout input
  - [x] Add save button
- [x] Integrate config query
- [x] Integrate config mutation
- [ ] Handle error
- [x] Block navigation with unsaved changes

### PR DESCRIPTION
**Pull request by nicolaslee2775**
close #529 

Removed `cookie_domain` and added `idle_timeout_enabled` input field.

image

### CODE REVIEW

**Review by axolotl0212 — APPROVED** [review]

**Comment by axolotl0212** [comment]
need to rebase

**Comment by nicolaslee2775** [comment]
Rebased

**Comment by louischan-oursky** [comment]
The unsaved change bar is not laid out in the correct position. Can you fix that?

**Comment by nicolaslee2775** [comment]
@louischan-oursky Fixed modified indicator position and adjusted settings screen padding size.

image

**Pull request merged**
