### PR TITLE
Add checking for add identity form

### PR DESCRIPTION
**Pull request by axolotl0212**
ref #680 

# screenshot

Screenshot 2020-10-30 at 4 46 19 PM

### CODE REVIEW

**Comment by louischan-oursky** [comment]
Conflicted. BTW, does this PR fix the problem described in #680 ?

**Comment by axolotl0212** [comment]
> does this PR fix the problem described in #680

@kiootic mentioned that if `login_id` is not included in identities, then user cannot create identity, so this PR add checking for login_id identity, show message to explain the situation if `login_id` is not included (for user going into page by URL). The add identity button is already disabled before.

Also, this case (`login_id` not included in identities) is not handled by backend (unhandled error is thrown), may be we need to handle the error in backend as well? As we cannot stop user from calling the API directly (not using portal)

**Comment by louischan-oursky** [comment]
We definitely need to handle password is required when new identity is added. So this PR does not fix #680 actually. Let me change the description.

**Comment by axolotl0212** [comment]
@louischan-oursky rebased

**Review by kiootic — APPROVED** [review]

**Comment by axolotl0212** [comment]
> We definitely need to handle password is required when new identity is added. So this PR does not fix #680 actually. Let me change the description.

@louischan-oursky opened PR https://github.com/authgear/authgear-server/pull/697 to fix this

**Pull request merged**
