### PR TITLE
Implement roles and groups filtering

### PR DESCRIPTION
**Pull request by tung2744**
ref #3986 
requires https://github.com/authgear/authgear-server/pull/4014

Screenshot 2024-03-20 at 6 57 00 PM
Screenshot 2024-03-20 at 6 56 33 PM

### CODE REVIEW

**Review by Ngkaokis — COMMENTED** [review]
I remember @fungc-io mentioned want the role/group filter auto expand to display the whole word?

image

**Comment by tung2744** [comment]
I think there must be a maximum, maybe I set it to minimum 100px (by figma), maximum 300px (same as search bar).
And in mobile, I think it should always occupy half of the column so I think we shouldn't let it expand.

**Comment by tung2744** [comment]
Here is an video demonstrating the behavior in different screen size:

https://github.com/authgear/authgear-server/assets/34942210/ec6b33df-9c30-429e-9c35-863903f57070

**Comment by Ngkaokis** [comment]
Merge first. Can open another issue if there is other styling issue

**Comment by fungc-io** [comment]
The filter box and responsive layout LGTM, 
thanks @tung2744 @Ngkaokis !

**Pull request merged**
