### PR TITLE
Fix some <Route> that have children does not have <Route index={true}>

### PR DESCRIPTION
**Pull request by louischan-oursky**
ref DEV-2367

### CODE REVIEW

**Review by tung2744 — APPROVED** [review]

**Comment by louischan-oursky** [comment]
Wait

**Comment by louischan-oursky** [comment]
I discovered one more problem.

**Comment by louischan-oursky** [comment]
@tung2744 Added some commits to fix the problem of error being entirely ignored in the previous approach. Now we use the error boundary provided by Sentry. It capture the error automatically, but still respect beforeSend. I also update isNetworkError to classify error produced by `import()`. The original work handle `fetch()` only.

**Review by tung2744 — APPROVED** [review]

**Comment by tung2744** [comment]
A lint failed

**Comment by louischan-oursky** [comment]
Added a commit to ignore the false positive.

**Pull request merged**
