### PR TITLE
Refactor bot protection secret key editing state management

### PR DESCRIPTION
**Pull request by pkong-ds**
## What's in this PR?

1. Fixes a bug where secretKey input field will show empty after saving a new secretKey
2. Now secretKey editing state is provider-specific (i.e. if cloudflare is not set before, the secretKey field will not be masked)

## Any regression?
Tested below ok

1. editing state should persist after reauthenticate
2. saving form ok

## Preview 1 - SecretKey masked after save

https://github.com/user-attachments/assets/7064d5b2-bef0-41d5-9756-34a09593d179

## Preview 2 - Diff. provider have diff. masked states

https://github.com/user-attachments/assets/7cfeeba2-2583-4cee-80b3-859e8743a245

## Preview 3 - editing state should persist after reauth

https://github.com/user-attachments/assets/f3c822d8-6a5c-442e-b9f8-53fb95bb002c

## Preview 4 - saving form ok

https://github.com/user-attachments/assets/5980deb3-66d3-4ff0-b119-3c26319fa541

### CODE REVIEW

**Review by louischan-oursky — CHANGES_REQUESTED** [review]
## Saving empty form gives empty error message

SCR-20240816-obiw

## Saving a form with the secret masked, will leave the secret NOT RESET

https://github.com/user-attachments/assets/8829fa03-ea00-4d05-8c0f-01f1bcb69d14

**Comment by pkong-ds** [comment]
Updated, thanks!

## Preview 5 - Saving empty site_key should show `Expect string with length greater than or equal to 1 character`

https://github.com/user-attachments/assets/008225a7-bab7-4acd-8062-d3578c45f05d

## Preview 6 - Saving empty secret_key should show `Please fill in this field`

https://github.com/user-attachments/assets/05149c90-425e-428a-9e42-cfe184433756
## Preview 7 - Saving `Disabled` bot protection should clear secrets

https://github.com/user-attachments/assets/41196b2e-bdd8-4aa6-9f66-382e40ee0da5

**Comment by louischan-oursky** [comment]
- Add useFormLoading hook
- Use useFormLoading hook in screen to disable the provider card on loading
- Fix the eslint error in the screen.

**Comment by pkong-ds** [comment]
@louischan-oursky thanks so much for helping me update this. I 
- fixed the lint errors
- added `useFormLoading` and used it with provider card
- opened issue https://linear.app/authgear/issue/DEV-1841/[portal-code-quality]-restritct-imports-of-dropdown

Thanks!

**Review by louischan-oursky — APPROVED** [review]

**Pull request merged**
