### PR TITLE
Adjust discard confirm dialog button design

### PR DESCRIPTION
**Pull request by andychow326**
ref #2249

### CODE REVIEW

**Review by carmenlau — COMMENTED** [review]
Better to adjust the dialog width so that the buttons can be aligned in the same row.

Screenshot 2022-08-01 at 4 04 05 PM

**Comment by louischan-oursky** [comment]
What about shortening the copy to "Discard and leave"? @fungc-io

**Comment by fungc-io** [comment]
@louischan-oursky good idea.

**Comment by andychow326** [comment]
Now the dialog looks like this
image

**Pull request merged**
